blank_issues_enabled: true
contact_links:
  - name: ğŸ’¬ é—®é¢˜è®¨è®º
    url: https://github.com/Lancernix/siyuan-mcp/discussions
    about: å¦‚æœä½ æœ‰ä½¿ç”¨é—®é¢˜ã€æƒ³æ³•äº¤æµæˆ–ä¸€èˆ¬æ€§å’¨è¯¢ï¼Œè¯·ä½¿ç”¨ Discussions
  - name: ğŸ“– æ–‡æ¡£
    url: https://github.com/Lancernix/siyuan-mcp#readme
    about: æŸ¥çœ‹é¡¹ç›®æ–‡æ¡£å’Œä½¿ç”¨è¯´æ˜
